Fix 'unused lifetime parameter' on lifetimes in with<>
Without it, code like this:

```
my_lender.flat_map(lender::covar_mut!(
    #![with<'g, G: SplitLabeling<Label=usize>>]
    for<'lend>
    move |(src, succ): (usize, <<G as SplitLabeling>::SplitLender<'g> as NodeLabelsLender<'lend>>::IntoIterator)|
    -> lender::FromIter<std::vec::IntoIter<(usize, usize)>> {
```

errors with:

```
error[E0392]: lifetime parameter `'g` is never used
  --> src/compress/transform.rs:79:41
   |
79 | ...                   #![with<'g, G: SplitLabeling<Label=usize>>]
   |                               ^^ unused lifetime parameter
   |
   = help: consider removing `'g`, referring to it in a field, or using a marker such as `std::marker::PhantomData`
```

Fixes regression in 8b3c7cd2be493845e79a65fa3df998fd8919fbe2.